<?php
  define('cashu','CashU');
  define('pm_cashu_accountid','Merchant ID');
  define('pm_cashu_seckey','Encryption Keyword');

  define('pm_cashu_return_callback_link','Return URL');
  define('pm_cashu_return_callback_link-tooltip','copy the text to your CashU merchant account panel.');
  define('pm_cashu_notify_callback_link','Notification URL');
  define('pm_cashu_notify_callback_link-tooltip','copy the text to your CashU merchant account panel.');
  define('pm_cashu_reject_callback_link','Sorry URL');
  define('pm_cashu_reject_callback_link-tooltip','copy the text to your CashU merchant account panel.');

  define('pm_cashu_test','Turn on testmode');

  define('pm_cashu_service_name','Service Name');
  define('pm_cashu_service_name-tooltip','Dont fill this when you use de "default" service name.');

  define('cashu_pay','Click here to redirect to the CachU site.');
  ?>
