<?php
/**
 *                   %%%copyright%%%
 *
 * FusionTicket - ticket reservation system
 *  Copyright (C) 2007-2013 FusionTicket Solution Limited . All rights reserved.
 *
 * Original Design:
 *	phpMyTicket - ticket reservation system
 * 	Copyright (C) 2004-2005 Anna Putrino, Stanislav Chachkov. All rights reserved.
 *
 * This file is part of FusionTicket.
 *
 * This file may be distributed and/or modified under the terms of the
 * "GNU General Public License" version 3 as published by the Free
 * Software Foundation and appearing in the file LICENSE included in
 * the packaging of this file.
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING
 * THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.
 *
 * Any links or references to Fusion Ticket must be left in under our licensing agreement.
 *
 * By USING this file you are agreeing to the above terms of use. REMOVING this licence does NOT
 * remove your obligation to the terms of use.
 *
 * The "GNU General Public License" (GPL) is available at
 * http://www.gnu.org/copyleft/gpl.html.
 *
 * Contact help@fusionticket.com if any conditions of this licencing isn't
 * clear to you.

**/

//Defines added at: 2013-10-29T08:53:01-07:00
//Modified: 
//Revision: 1955

define('cashu', 'CashU');

define('pm_cashu_accountid', 'Merchant ID');
define('pm_cashu_seckey', 'Encryption Keyword');
define('pm_cashu_return_callback_link', 'Return URL');
define('pm_cashu_return_callback_link-tooltip', 'copy the text to your CashU merchant account panel.');
define('pm_cashu_notify_callback_link', 'Notification URL');
define('pm_cashu_notify_callback_link-tooltip', 'copy the text to your CashU merchant account panel.');
define('pm_cashu_reject_callback_link', 'Sorry URL');
define('pm_cashu_reject_callback_link-tooltip', 'copy the text to your CashU merchant account panel.');
define('pm_cashu_test', 'Turn on testmode');
define('pm_cashu_service_name', 'Service Name');
define('pm_cashu_service_name-tooltip', 'Dont fill this when you use de "default" service name.');

define('cashu_pay', 'Click here to redirect to the CachU site.');
?>