<?php
  define('reminders_list', 'Reminders');
  define('reminder_title', 'List of all reminders');
  define('reminder_form_title', 'Reminder settings');

  define('reminder_name', 'Reminder title');
  define('reminder_ident', 'Reminder weight');
  define('reminder_days', 'days before reminder');
  define('reminder_email', 'eMail template');
  define('reminder_pdf', 'PDF template');
  define('reminder_fee', 'Reminder fee');
  define('reminder_text', 'Description');
  define('reminder_color', 'Color');
  define('reminder_id', 'Reminder id');

  define('reminder_ident_th', 'Weight');
  define('reminder_name_th', 'Name');
  define('reminder_days_th', 'Days');
  define('reminder_email_th', 'eMail');
  define('reminder_pdf_th', 'PDF');
  define('reminder_fee_th', 'Fees');

  define('reminder_activate_question', 'Do you want to activate this reminder?');
  define('reminder_deactivated', 'Deactivated');
  define('reminder_deactivate_question', 'Do you want to deactivate this reminder?');
  define('reminder_activated', 'Activated');

  define('reminders_orders', 'Reminders');

  define('reminder_activate', 'Activate reminder ');
  define('reminder_order_question', 'Send the reminder now?');
  define('send_reminder', 'Send reminder');

  define('reminder_order_id_th', 'Order');
  define('reminder_order_date_th', 'Order date');
  define('reminder_order_total_th', 'Total price');
  define('reminder_order_reminder_th', 'Reminders');
  define('reminder_next_to_be_send_in', 'next in ');
  define('reminder_next_days', ' days.');

  define('reminder_need_to_be_send', ' needs to be sent!');
  define('reminders_order_title', 'Show All unpaid orders!');

  define('reminder_is_send_on', ' is send on ');
	
	define ('TABLE_STATS','userstats');
 ?>