<?php
  define("moda_0","Statistics are currently disabled for this installation. You must enable this option as an advanced configuration option in the core application by setting the class var EnableWebStats to 1");
  define("moda_1","Top 10 Visitors");
  define("moda_2","Unique Vistors");
  define("moda_3","Top 10 Browsers");
  define("moda_4","Unique Browsers");
  define("moda_5","Top 10 Referrers");
  define("moda_6","Statistics Log");
  define("moda_7","Clear Statistics Log");
  define("moda_8","Last");
  define("moda_9","Next");
  define("moda_10","Stats Log Cleared");
  define("moda_11","Site Statistics");
  define("moda_12","Top 10 Requests");
  define('useraccess_list','Access Log');
?>