<?php
/**
 *                   %%%copyright%%%
 *
 * FusionTicket - ticket reservation system
 *  Copyright (C) 2007-2013 FusionTicket Solution Limited . All rights reserved.
 *
 * Original Design:
 *	phpMyTicket - ticket reservation system
 * 	Copyright (C) 2004-2005 Anna Putrino, Stanislav Chachkov. All rights reserved.
 *
 * This file is part of FusionTicket.
 *
 * This file may be distributed and/or modified under the terms of the
 * "GNU General Public License" version 3 as published by the Free
 * Software Foundation and appearing in the file LICENSE included in
 * the packaging of this file.
 *
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING
 * THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.
 *
 * Any links or references to Fusion Ticket must be left in under our licensing agreement.
 *
 * By USING this file you are agreeing to the above terms of use. REMOVING this licence does NOT
 * remove your obligation to the terms of use.
 *
 * The "GNU General Public License" (GPL) is available at
 * http://www.gnu.org/copyleft/gpl.html.
 *
 * Contact help@fusionticket.com if any conditions of this licencing isn't
 * clear to you.

**/

//Defines added at: 2013-11-05T11:31:41-08:00
//Modified: 1
//Defines added at: 2013-11-05T08:10:03-08:00
//Revision: 1955

define('split_pm', "Split Seat Chart");

define('ballet', "Ballet");

define('export_xml_event_event', "Choose an Event");

define('prg_complete', "Complete Order");

define('include_invoice', "Include Invoice");

define('configuration_is_saved', "Configuration is saved.");

define('status_is_pub', "This Event is Published!");

define('blues', "Blues");

define('export_xl', "Sales Data");

define('no_handling_selected', "No handling method selected.");

define('include_tickets', "Include Tickets");

define('stop_success', "Successfully Stopped!");
define('sacred', "Church music");

define('xl_view_title', "Sales Data");

define('noting_checkout', "There is nothing to checkout!!!");

define('cant_create_seat_zone_missing_cat', "Every zone needs to have category in a placemap part.");

define('please_wait_button', "Please wait.");

define('system_halted', "<b>SYSTEM IS HALTED!<b>");

define('cinema', "Cinema");

define('xl_start', "Date of sales");

define('no_useraddress_selected', "No user address selected.");

define('pub_success', "The following event has been successfully published: ");
define('please_wait_message_order', "Please wait, will the order is created.");

define('this_page_is_not_secure', "Attention: Your Registration and Order Details are not encrypted. However payments using Paypal will use secure pages (SSL).");

define('classics', "Classical music");

define('xl_end', "End Date");

define('error_missingcategorytype', "Missing category numbering type");

define('vpc_pay', "Proceed to payment gateway page");

define('site_offline_message', "PLEASE NOTE: This Site is off-line.");

define('ticket_deleted', "Ticket Deleted!");

define('exposition', "Exposition");

define('generate_xl', "Generate Sales Worksheet");

define('error_discountnotfound', "Discount not found");

define('successfully_updated_user_details', "Your profile has been successfully updated.");

define('export_eventbarcodes_order', "Order ID");

define('ticket_not_found', "Ticket Not Found in Database!");

define('folklore', "Folklore");

define('seat_id', "Ticket Number");

define('event_sold', "Event sold out");

define('payment_not_approved', "Payment is not approved.");

define('order_payment', "Payment");

define('tickets_printing', "Tickets are Printing. Please Wait!");

define('funk', "Funk");

define('seat_price', "Seat Price");

define('dts_month_arr', "January|February|March|April|May|June|July|August|September|October|November|December");

define('publish_web', "Publish to Webshop");

define('too_low', "Please Enter a Number Larger than 0 !");

define('humour', "Humour");

define('export_cc', "Credit Cards");

define('without_fee', "Without Fee");

define('unpublish_web', "Remove from Webshop");

define('garbage_images', "Garbage images");

define('to_trash', "Sent to Garbage");

define('jazz', "Jazz");

define('export_cc_title', "Export Credit Card Numbers");

define('without_cost', "Without Cost");

define('cant_delete_without_id', "Missing record definition");

define('undefined', "Undefined!");

define('music', "Music");

define('export_cc_count', "Credit Card Count");

define('box_office', "Box Office");

define('ftsmanager_plugin', "FTS hosting manager");

define('err_blank_or_allready', "Error, Blank or already in use!");

define('opera', "Opera");

define('export_entrant', "Export Attendees");

define('alert', "Alert:");

define('icon_webpub', "Click to Publish to Webshop");

define('valutas', "Common valutas");

define('compilation_failed', "Compilation Failed!");

define('other', "Other");

define('export_entrant_title', "Ticket Status Report");

define('pos_booktickets', "Book Tickets");

define('icon_webpub_alt', "Publish to Webshop");

define('pm_mollie_bank_id', "Bank relatie:");

define('classcatch', "Class Catch:");

define('party', "Party");

define('export_entrant_event', "Choose an Event");

define('seat_count', "Seat Count:");

define('icon_webunpub', "Click to Remove from Webshop");

define('handling_', "Unknown handler");

define('wrong_input_ids', "Wrong Input Id");

define('pop', "Pop");

define('export_entrant_order_id', "Order ID");

define('pos_order_page', "Order Checkout");

define('icon_webunpub_alt', "Remove from Webshop");

define('xl_order_place', "Place");

define('file_not_exsist', "File does Not Exist!");

define('rock', "Rock");

define('export_entrant_fullname', "FullName");

define('free_seat', "Seats Available:");

define('icon_pospub', "Click to Publish to POS");

define('xl_handling_payment', "Handled");

define('username_not_found', "User not registered. Please provide a valid email.");

define('sports', "Sports");

define('export_entrant_city', "City");

define('open_event', "Open Event?");

define('icon_pospub_alt', "Publish to POS");

define('linked_event_managers', "Linked managers");

define('search_choice_one_field', "Choose a Field to Search!");

define('theater', "Theater");

define('export_entrant_tickets', "Tickets");

define('actions', "Actions");

define('icon_posunpub', "Click to Remove from POS");

define('select_event_group', "Select an Event Group");
define('search_choice_event', "Choose an Event to Search!");

define('event_image', "Event Image");
define('export_entrant_price', "Total Due");

define('timestamp', "Timestamp");

define('icon_posunpub_alt', "Remove from POS");

define('group_webshop_ads', "Google ads");

define('search_choice_seat_row_nr', "Choose a Seat/Row to Search!");

define('event_mp3', "MP3");
define('export_entrant_totalprice', "Totals");

define('cancel_and_delete', "Status Changed to &quot;Cancelled&quot; and Tickets Deleted");
define('cc_name', "Credit card owner name");

define('google_ad_client', "Google ads client is [pub-...]");

define('options_saved', "Options Saved!");

define('undefined_category', "Category undefined");

define('export_entrant_seats', "Seats");

define('order_details', "Order details");

define('cc_number', "Credit card number");

define('google_ad_slot_left', "Slot ID left ads");

define('update_error', "Update Error!");

define('discount_title', "Discounts");

define('time', "Time");

define('order_status_changed', "Order Status Changed Successfully");

define('cc_exp', "Expiry date");

define('google_ad_slot_right', "Slot ID right ads");

define('user_details_saved_successfully', "User details successfully updated");

define('discount_add_title', "Add a Discount");

define('import_admin_title', "Import Data");

define('pos_currenttickets', "Orders Overview");

define('cc_code', "Security code");

define('al_remove_control', "Remove link");

define('index_admin', "Home");

define('discount_category_id', "Event Category");

define('import_xml_title', "Import Files");

define('pos_yourtickets', "Owned Orders");

define('error', "error");

define('unpub_success', "Event success unpublished.");

define('administration', "Administration");

define('discount_cond', "Discount Conditions");

define('import_xml_submit', "Import It!");

define('pos_alltickets', "All Paid/Sent Orders");

define('select_qty', "Select quantity");

define('handling', "Handling");

define('tabs-admins_admin', "User Management");

define('discount_update_title', "Modify Discount");

define('import_xml', "Event in XML");

define('pos_paidlist', "Paid orders");

define('successfully_add_note', "Note successfully added");

define('pmz', "Zone");

define('tabs-events_admin', "Event Management");

define('discount_id', "Discount ID");

define('import_xml_file', "Import File");

define('pos_unsentlist', "UnSent Orders");
define('please_select', "Please select...");
define('pmp', "Placemap Part");

define('statistic_admin', "Reporting");

define('discount_name', "Discount Name");

define('import_template', "Templates");

define('pos_unpaidlist', "UnPaid List");

define('filter', "Search");

define('barcode', "Barcode");

define('orders_admin', "Order Management");

define('discount_type', "Discount Type");

define('import_langauge', "Language Files");

define('pos_reservedlist', "Reserved Orders");

define('venue_in_use', "This venue is in use.");

define('no_template_tags', "email template looks empty");

define('template_admin', "Templates");

define('discount_type_fixe', "Fixed Discount");

define('import_csv_file', "Import File Name");

define('paymentstatus', "Payment Status");
define('print_both', "Print invoice & ticket");

define('emailtest', "Send test email");

define('handlings_admin', "Order Handlings");

define('discount_type_percent', "Percent Discount");

define('langauge', "New Language File Name");

define('pos_clicktoproc', "Click To Finish Processing!");

define('view_details', "View order details");

define('testemail_notsend', "Test Email was not send.");

define('search_admin', "Search");

define('discount_value', "Discount Value");

define('orphan_tab', "Orphans");

define('pos_clicktosent', "Click To Set to Sent!");

define('cannot_find_order', "Cannot find order");

define('testemail_was_send_to', "A test email was send to ");
define('transports_admin', "Import /Export");

define('event_stats_title', "Statistics");

define('pos_deleteorder', "Delete Order?");

define('main', "Main event");

define('cant_set_new_password', "Problem with changing the password.");

define('utilities_admin', "Utilities");

define('show_text_stats', "Text");

define('garbage_tab', "Garbage");

define('pos_handlinginfo', "Handling Info");

define('control', "Ticket Taker");

define('no_category_selected', "No Category selected");

define('index_admin_tab', "Information");

define('show_grafik_stats', "Graph");

define('garbage', "Garbage");

define('pos_enternote', "Notes about order and tickets:<br><b>Remember to save after any changes!!</b>");

define('ticket', "ticket");

define('availability', "View Availability");

define('current_version', "Version:");

define('event_status', "Event Status");
define('empty_trash', "Empty");

define('pos_goback', "Click to go back");

define('failed_send_to', "Failed to send an Email.");

define('event_sales_closed_header', "Ticket sales are not open. You can view availability by clicking View Availability");

define('infowebversion', "Server Software");

define('event_status_active', "Active");

define('unused_guests', "Unused Guests");

define('pos_nextorder', "Next Order");

define('admin_status_control', "Ticket taker");

define('event_ordering_header', "Ticket sales are not open. You can view availability by choosing a category");

define('infophpversion', "PHP Version");

define('event_status_all', "All");

define('order', "Orders");

define('pos_nextunpaid', "Next UnPaid Order");

define('admin_status_pos', "POS User");

define('event_ordering_sales_closed_no_seatmap', "No seat map available for this category.");

define('infomysqlversion', "MySQL Version");

define('orders_handlings_tab', "Handling");

define('emaillog_tab', "Email Log");

define('pos_nextunsent', "Next UnSent Order");

define('admin_status_posman', "POS Manager");

define('event_prices_sales_closed_footer', "Tickets are not available at this moment.");

define('infomysqldb', "Database");

define('orders_event_tab', "Events");

define('email_log_list_title', "Email List");

define('pos_processorder', "Processed Order? The Order ID and Ticket IDs been noted?");

define('admin_status_organizer', "Organizer");

define('event_sales_open', "Event Sales Open");

define('infousercount', "User count:");

define('orders_view_asc', "Sort by Event date: Ascending");

define('el_timestamp', "Date Sent");

define('pos_reorder_info', "To Order Tickets Click below:<br>WARNING old order is cancelled on Re-Order!");

define('admin_status_accountant', "Accountant");

define('event_sales_close', "Event Sales Close");

define('infogroupcount', "Group count:");

define('orders_view_desc', "Sort by Event date: Descending");

define('el_action', "Action");

define('pos_ticketready', "The tickets have there ID and Order ID on them and are ready to to be posted?");

define('admin_status_admin', "Administrator");

define('reservtime', "Time left");

define('infovenuecount', "Venue count:");

define('order_list_title', "Orders by Payment Handling");

define('el_email_to', "Addressed To:");

define('shipmentstatus', "Shipment Status");

define('admin_status_tickettaker', "Tickettaker");

define('payreservenow', "Pay reservation");

define('infoeventcount', "Event count:");

define('order_event_list_title', "Orders by Event");

define('el_failed', "Failed");

define('next_order_id', "Next Order ID");

define('admin_status_manager', "Manager");

define('export_eventbarcodes_seat', "Seat");

define('infoadmincount', "Admin count:");

define('order_type_ordered', "Ordered");

define('el_received', "Received");

define('cancel_ticket', "Cancel Ticket");

define('role_not_allowed', "Role not allowed.");

define('export_eventbarcodes_seat_free', "Free");

define('system_summary', "System Summary");

define('order_type_pending', "Pending");

define('el_log', "Return Log");

define('reissued', "Re-issued");

define('error_nosizediff', "No new size given.");

define('select_seats_first', "Select seats first");

define('index_admins_count', "<b>Admins:</b> %d, <b>Managers:</b> %d, <b>Pos:</b> %d, <b>TicketTakers:</b> %d");

define('order_type_cancelled', "Cancelled");

define('el_bad_emails', "Bad Emails");
define('exist_user', "Existing");

define('category_nosale_size', "Category Size");

define('select_seats', "Select seats");

define('index_user_count', "<b>POS:</b> %d, <b>Guests:</b> %d, <b>Members:</b> %d/%d/%d");

define('order_type_reissued', "Re-issued");

define('el_email_message', "Email Message");

define('new_partron', "New");

define('plugin_install_title', "Plugins");

define('search_user_details', "User information");

define('index_events_count', "<b>Pub:</b> %d, <b>New:</b> %d, <b>Nosale:</b> %d, <b>Trash:</b> %d, <b>Total:</b> %d");

define('order_type_paid', "Paid");

define('backup_tab', "Backup");

define('open_with_acrobat', "Open Orders in Acrobat");

define('plugin_name', "Pluginname");

define('tickettaker_change_event', "Change Event");

define('index_ort_count', "%d");

define('order_type_sended', "Sent");

define('backup_title', "Back Up Database");

define('preferences', "Preferences");
define('plugin_info', "Plugin information");

define('tickettaker_logout', "Logout");

define('owner_tab', "Merchant Details");
define('order_type_reserved', "Reserved");

define('comp_method', "Compression Method");

define('send_orders_printer', "Send Orders to Printer");

define('plugin_myversion', "Version number");

define('tickettaker_scan', "Scan tickets");

define('merchant_update_title', "Modify Merchant Information");

define('purge', "Purge");

define('comp_level', "Compression Level");

define('select_country', "Select Country...");

define('plugin_priority', "Priority");

define('tickettaker_search', "Search");

define('organizer_name', "Merchant Name");
define('order_patron', "Customer");

define('bzip2', "BZip2");

define('eph_cash_confirm', "The order is created, press &quot;Pay&quot; to continue.");

define('plugin_priority_5', "5");

define('search_order_id_header', "Order #");

define('organizer_address', "Address");
define('order_nr', "Order #: ");

define('gzip', "GZip");

define('page_format_default', "Default");
define('plugin_priority_4', "4");

define('search_order_date_header', "Date");

define('organizer_plz', "Zip");
define('order_tickets_nr', "Number of Tickets");

define('without_compression', "Without Compression");

define('page_format_std', "Standard");
define('plugin_priority_3', "3");

define('search_user_header', "Patron");

define('organizer_ort', "City");

define('tickets_nr', "Quantity");

define('change_event', "Change Event");

define('page_format_custom', "Custom");
define('plugin_priority_2', "2");

define('search_address_header', "Address");

define('organizer_state', "State");
define('order_fee', "Fee");

define('check', "Check");

define('page_orientation_landscape', "Landscape");
define('plugin_priority_1', "1");

define('search_zip_header', "Zip");

define('organizer_country', "Country");
define('order_total_price', "Total Price");

define('checked', "Checked");

define('page_orientation_portrait', "Portrait");
define('plugin_enabled', "Enabled");

define('search_city_header', "City");

define('organizer_phone', "Phone");
define('order_date', "Order Date");

define('check_success', "Ticket Check OK!");

define('place_row', "Row");
define('plugin_protected', "Protected plugin");

define('search_country_header', "Country");

define('organizer_fax', "Fax");
define('order_shipment_status', "Shipment Status");

define('com', "Ordered");

define('place_seat', "Seat");
define('plugin_allow_uninstall', "Are you sure to uninstall this plugin?");

define('search_order_status_header', "Status");

define('organizer_email', "E-Mail");
define('order_place', "Order created at");

define('control_events_list', "Events");

define('payment_cc', "Credit Card");

define('discount_www_deactivate', "Deactivate this Discount for the webshop?");

define('search_seat_id_header', "Seat #");

define('organizer_currency', "Currency");
define('order_admin', "Order created by");

define('free', "Free");

define('payment_post', "Post");

define('discount_pos_deactivate', "Deactivate this Discount for the Points of Sale?");

define('search_event_name_header', "Event");

define('organizer_logo', "Merchant's Logo");

define('send', "Sent");

define('not_valid_event', "Event is Not Valid");

define('paypal_pay', "Make payments with PayPal - it's fast, free and secure!");

define('discount_www_activate', "Activate this Discount for the webshop?");

define('search_category_name_header', "Category");

define('organizer_remove_image', "Remove Logo");
define('order_payment_status', "Order Status");

define('place_not_commanded', "Seat is Not Ordered");
define('pm_title', "Charts");

define('discount_pos_activate', "Activate this Discount for the Points of Sale?");

define('search_pmz_name_header', "Zone");
define('shopconfig_tab', "Configuration");

define('order_paid_total_view', "Order Total");

define('place_only_reserved', "Seat Reserved, but Not Paid");

define('tmp_receipt', "Receipt");

define('discount_www_activated', "Active in the webshop");

define('search_place_header', "Seat");

define('option_update_title', "Config Shop Auto-Cleanup settings.");
define('order_payment_id', "Payment ID");

define('place_status_not_updated', "Error: Seat Status Not Updated");

define('tmp_invoice', "Invoice");

define('discount_pos_activated', "Active in the Points of Sale");

define('search_seat_status_header', "Status");
define('shopconfig_lastrun_int', "Cleanup check interval (0 = off)");

define('order_status', "Status");

define('place_without_nr', "Seat Without Number");

define('tmp_sold_to', "Sold To:");

define('discount_pos_deactivated', "Deactive in the Points of Sale");

define('checkin_ticket', "Are you sure to checkin this ticket?");

define('shopconfig_lastrun', "Last time checked");

define('processed', "Processed");

define('ticket_already_checked', "Ticket Already Checked");
define('tmp_order_date', "Order Date");

define('discount_www_deactivated', "Deactive in the webshop");

define('checkin', "Checkin");

define('date_format', "%A - %B %e, %Y");

define('shopconfig_restime', "Reservation time (0 = off)");

define('order_deleted_manual', "Order Manually cancelled");

define('header_ticket_taker', "Ticket Takers");

define('tmp_order_number', "Order Number");

define('handling_www_deactivate', "Deactivate this handling for the webshop?");

define('search_result_none', "No search result for this selection.");

define('time_format', "%I:%M %p");

define('shopconfig_check_pos', "Check for Unpaid POS Orders?");

define('order_responce', "Cancellation Type");

define('no_event_sets', "There are no events scheduled at this moment, please check back later.");

define('tmp_order_method', "Order Method");

define('handling_pos_deactivate', "Deactivate this handling for the Points of Sale?");

define('checkout_expired', "The tickets in you cart are expired \\nand will be removed from the cart.");

define('admin_date_format', "Y-m-d");

define('confirm_yes', "Yes");

define('order_responce_date', "Cancellation Date");

define('no_event_groups_sets', "There are no festivals scheduled at this moment, please check back later.");

define('tmp_shipping_method', "Shipping Method ");

define('handling_www_activate', "Activate this handling for the webshop?");

define('no_user_set', "User not selected.");

define('admin_time_format', "H:i");

define('confirm_no', "No");

define('order_delete_now', "Are you sure to remove this order?");

define('act_name', "Activate Account");

define('tmp_payment_method', "Payment Method");

define('handling_pos_activate', "Activate this handling for the Points of Sale?");

define('event_status_header', "Status");

define('admin_datetime_format', "Y-m-d H:i");

define('shopconfig_delunpaid', "Global Delete Unpaid Orders?");

define('order_details_tickettab', "Tickets");

define('act_done', "Account Activated");

define('tmp_description', "Description");

define('handling_www_activated', "Active in the webshop");

define('event_name_header', "Events");

define('longdate_format', "%Y-%m-%d %H:%M:%S");

define('shopconfig_delunpaid_pos', "Delete UnPaid POS Orders?");

define('order_details_usertab', "User");

define('act_enter_title', "Kindly enter your activation code below.");

define('temp_quantity', "Qty.");

define('handling_pos_activated', "Active in the Points of Sale");

define('event_datetime_header', "Date");

define('shortdate_format', "%e %b %Y");

define('option_others_title', "Other Options");
define('order_details_logtab', "Status log");

define('act_enter_code', "Complete your activation by entering the activation code sent to you by Email in the box below, or click on the link in the Email.<br/>If you have already activated your account, please press Activate again");

define('tmp_category', "Category ");

define('handling_pos_deactivated', "Deactive in the Points of Sale");

define('event_type_header', "Type");

define('shorterdate_format', "%h %e");
define('shopconfig_user_activate', "Users Checkout Level");

define('order_details_notetab', "Note");

define('act_code', "Activation code");

define('tmp_discounts', "Discounts");

define('handling_www_deactivated', "Deactive in the webshop");

define('ort_name_header', "Venue");

define('date', "Date");

define('act_restrict_cart', "Restrict Cart to Members");

define('order_statuslog', "Order status log");

define('act_send', "Activate");

define('tmp_price', "Price");

define('new_category_size_not_different', "The new category size should be different from the old one.");

define('ort_country_header', "Country");

define('dd_mm_yyyy', "(dd-mm-yyyy)");

define('act_restrict_all', "Only activated members");

define('order_note', "Don't forget to save the note.");

define('act_notarr', "Resend Activation");

define('tmp_total', "Total ");

define('event_status_incorrect', "In order to resize a category, the event should be unpublished");

define('actions_header', "");

define('yyyy_mm_dd', "(yyyy-mm-dd)");

define('act_restrict_later', "New members are allowed");

define('order_note_title', "Note");

define('resend_activation', "Resend Activation");

define('tmp_subtotal', "SubTotal:");

define('category_numbering_incorrect', "Only open seated categories can be resized");

define('multicurrency_conf', "Currency Conversion Rates");

define('date_from', "Date From");

define('act_restrict_w_guest', "New members and guests");

define('order_add_note', "Add Note");

define('act_is_sent', "Your Activation Email has been sent to your inbox.");

define('tmp_fee', "Handling Fee:");

define('new_category_size_is_to_small', "New category size should be at least equal to sold seats in that category.");

define('datatable_no_data', "No data available in table");
define('date_to', "Date To");

define('act_restrict_quest_only', "Only guest users");

define('onote_type', "Note Type");

define('act_sent', "Your activation email has been sent to your inbox. Please check your Email for the activation code or link.");

define('tmp_order_total', "Total:");

define('cant_lock_event', "Cannot lock event to allow this change.");

define('datatable_loading', "Loading...");
define('dts_day_arr', "Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday");

define('shopconfig_maxres', "Max tickets to reserve");

define('on_type_note', "Generic Note");

define('act_resent', "Your activation email has been resent to your inbox. Please check your Email for the activation code or link.");

define('tmp_thank_you', "Thank You!");

define('size_to_small_for_event', "Free seat at the event is not sufficient");

define('datatable_zerorecords', "No matching records found.");

define('add', "Add");

define('shopconfig_altpayment_time', "Switch to Alt Payment");

define('on_type_admin', "Admin Note");

define('act_mess_line', "Please check your email to activate your account.<br>");

define('tmp_inv_message', "Your tickets have been reserved. Please pay this invoice within 10 minutes.");

define('cant_delete_old_seats', "Cannot delete old seats");

define('eventlink_check_header', "");

define('add_row', "Add");

define('res_delay', "Shopping Cart Timeout");

define('on_type_action', "Action/ToDo");

define('act_mess_line_nm', "<b>You may complete this order without activating your account.</b><br>
          					Please check your email to activate your account for future purchases.<br>");

define('tmp_flourish', " Presents");

define('cant_save_category', "Cannot save category statistics");

define('eventlink_loginname_header', "Loginname");

define('add_venue', "Add ");

define('cart_delay', "Database Cart Timeout");

define('on_type_payment', "Payment Details Note");

define('act_note', "Enter your e-mail address. Click on 'Resend Activation' and a new activation email will be sent to your e-mail address.");

define('tmp_venue', "Location Details");

define('admin_country', "User Country");

define('eventlink_email_header', "email address");

define('add_tickets', "Add Ticket(s)");

define('res_delay_less_cart', " < Can not be less than Cart Timeout");

define('on_type_ship', "Shipping Details Note");

define('act_norecived', "If you have not received an activation email within a few hours, please click this <strong>link</strong>");

define('tmp_date_time', "Date and Time");

define('report_excelcolors', "report_excelcolors");

define('update', "Update");

define('admin_list', "List");
define('admin_login', "Login Name");

define('on_type_todo', "ToDo");

define('success_activate', "You have successfully activated your account. You are now logged in.");

define('tmp_event_date', "Event Date:");

define('no_event_data', "Your cart has timed out and is now empty.");

define('pos_event_name_title', "Events");

define('cancel', "Cancel Order?");

define('admin_user_tab', "Administrators");

define('note', "Note");

define('agb_name', "General Terms of Sale");

define('tmp_start_time', "Start Time: ");

define('status_change_handling_error', "Error while changing status.");

define('pos_tickets_title', "Tickets");

define('checkout', "Checkout");

define('admin_id', "Admin ID");
define('admin', "Administrator");
define('agb_info', "Put your sales conditions in 'agb.html'");

define('tmp_open_time', "Doors Open: ");

define('pub', "Published Events");
define('pos_total_title', "Total");

define('clear', "Clear");

define('admin_inuse', "Enabled?");

define('ship', "Shipping");

define('calendar', "Calendar");

define('tmp_section', "Seating Section");

define('unpub', "Unpublished Events");

define('pos_event_name', "Event");

define('close', "Close");

define('admin_ismanager', "Is manager");

define('pos', "POS User");

define('cart_empty', "Your Cart is Empty.");

define('tmp_zone', "Zone:");

define('nosal', "Not on sale");

define('pos_date', "Date");

define('continue', "Continue");

define('admin_user_title', "System Administrators");

define('posman', "POS Manager");

define('cart_empty_or_invalid', "The cart is empty or invalid. Please add tickets.");

define('tmp_row', "Row #: ");

define('nextbutton', "Next");

define('pos_venue', "Venue");

define('define', "Define");

define('admin_update_title', "Modify Administrator");

define('organizer', "Organizer");

define('total', "Total");
define('tmp_seat', "Seat#: ");

define('handling_sp', "POS");

define('pos_doors_open', "Doors open");

define('edit', "Edit");

define('admin_add_title', "Add System Administrator");

define('change_status_to_ord', "Change Status to Ordered?");

define('expires_in', "Expires in");

define('tmp_details', "Ticket Details");

define('handling_www', "WEB");

define('wrong_event_id', "Wrong event_id!");

define('delete', "Delete");

define('spoint_tab', "POS Offices");

define('change_status_to_send', "Change Status to Sent?");

define('total_price', "Total Price");
define('tmp_type', "Type: ");

define('for_handling_salemode', "for: ");

define('discount_none', "None");

define('login_button', "Login");

define('pos_user_title', "Points of Sale");

define('change_status_to_no_send', "Change Status to Not Sent?");

define('shopcart', "Shopping Cart");

define('tmp_discount', "Discount: ");

define('you_requested_that_is_not_visable', "The requested page is not available.");

define('placemapexit', "Exit");

define('order_it', "Order");

define('pos_add_title', "Add a Point of Sale");

define('change_status_to_paid', "Change Status to Paid?");

define('no_tick_res', "You have no reserved tickets.");

define('tmp_conditions', "<b>NOTE TO PURCHASER: TREAT THIS E-TICKET AS YOU WOULD ANY OTHER VALUABLE OR CASH. YOU WILL NEED TO PRINT THIS AND PRESENT IT WHEN COLLECTING YOUR PHYSICAL TICKET.</b>
Unauthorised duplication, alteration, or sale of this ticket may prevent admittance to the event.
Present this page at the time of admission to be scanned.
The unique bar code on this ticket allows only one entry per ticket.");

define('you_do_not_have_access', "Sorry, You do not have access to this function.");

define('select_event_first', "<b style=\"text-align:center;width:100%;\">No event selected.</b>");

define('order_more_tickets', "Buy More Tickets");

define('pos_update_title', "Modify Point of Sale");

define('change_status_to_no_paid', "Change Status to Not Paid?");

define('valid_tickets', "Valid Tickets:");

define('login_pos', "POS Login");

define('order_seats', "order_seats");

define('pos_event_image_header', "Image");
define('publish', "Publish");

define('kasse_name', "POS Name");

define('reissue_order', "Update this order and re-issue with new tickets?");

define('expired_tickets', "Expired Tickets:");

define('login_organizer', "Administration Login");

define('templ_files', "Template Files");

define('pos_event_description_header', "Description");
define('pwd_send', "Send Password");

define('user_prefs_print', "Preferences");

define('reissue_ticket', "Re-issue the ticket (recalculate unique barcode)? Ticket Nr:");

define('tick_exp_in', "Expiring in ");

define('login_control', "Ticket Taker Login");

define('discount_used', "discount used");

define('select_event', "Select an Event");

define('remove', "Remove");

define('user_prefs_print_pdf', "Open Orders in Acrobat");

define('legende', "Explanation");

define('x_tick', "x Tickets");

define('approx', "Approx");

define('plugin_config_title', "Plugin configuration");

define('help_plugin', "Help plugin");

define('res', "Reset");

define('user_prefs_print_pdt', "Send Orders to Printer");

define('reserved', "Reserved");

define('tot_tick_price', "Total Ticket Price:");

define('pay', "Proceed to payment");
define('pub_failure', "Cannot publish event");

define('search_action', "Click to show the list of existing users");

define('reserve', "Reserve");

define('user_prefs_strict', "Use Office On fixed PC");

define('ordered', "Ordered");

define('row', "Row");

define('not_all_all_values_set', "Check your form, not all needed values where set for Re-Occurs.");

define('error_event_save_changes', "error when trying to save changes");

define('order_action', "Click to create the order");

define('save', "Save");

define('user_prefs_store_now', "Store cookie now");

define('pending', "Pending");

define('normal', "Normal");

define('email_compile_error', "Compile error: ");

define('stop_failure', "Cant stop event");

define('order_cancel_action', "Cancel the defined order");

define('save_payment', "Save &amp; Email payment note");

define('user_nickname', "Nickname");

define('paid', "Paid");

define('expired', "EXPIRED");

define('order_discount_price', "Discount amount");

define('restart_failure', "Cant restart event");

define('notifytimeout', "Notify Message closetime");

define('save_ship', "Save &amp; Email shipping note");

define('print_warning', "When you want to directly print the PDF's, you need to setup our system.");

define('sended', "Sent");

define('minutes', "min.");

define('order_partial_price', "Order Price");
define('order_status_ordered', "ordered");

define('group_eventsettings', "Event Settings");

define('save_note', "Save &amp; Email a note");

define('control_tab', "Ticket Takers");

define('paid_and_send', "Paid and Sent");

define('selected_total', "Selected Ticket Total in ");

define('discount_promo', "Discount promo code");

define('admin_default', "Default");
define('archive_oldevents', "Move Event Direct to Archive");

define('search', "Search");

define('control_user_title', "Ticket Takers");
define('cancelled', "Cancelled");

define('shopping_cart', "Shopping cart");

define('global_discounts', "Order Discounts");

define('eprocessingnetwork', "eProcessingNetwork");

define('order_already_reissue_cancelled', "Order already reissue cancelled!");

define('show_seats', "Seating Chart");

define('control_view', "Ticket Taker");

define('reissue', "Re-issued");

define('cart_cont_mess', "Please check your order. You have a limited time before your reserved tickets are released back to sale. Please, either order more tickets or continue to checkout.
	<br><br>To change your tickets 'Remove' the ones you have reserved and click 'Order More Tickets'.");

define('down_install_again', "Install new version");

define('maroc', "maroc");

define('category_numbering_header', "Nature");

define('submit', "Submit");

define('control_add_title', "Add Ticket Taker");

define('possible_actions', "Possible Actions");

define('cat_description', "Seating Sections and Prices");

define('version_checker', "Install new version");

define('maroctelecommerce', "maroctelecommerce");

define('category_name_header', "Category");

define('unpublish', "Unpublish");

define('control_update_title', "Modify Ticket Taker");

define('view_order_details', "View Details");

define('tickets_available', "Availability");

define('avaliable_version', "Available version");

define('mollie', "mollie");

define('category_size_header', "Size");

define('view', "View");

define('control_login', "Login Name");

define('print_order', "Print Order");

define('category_sold', "Sold out");
define('curr_ver', "Current version");

define('vpc', "vpc");

define('category_price_header', "Price");

define('view_order', "View Order");

define('control_event_ids', "Authorised Events");
define('change_order_to_ord', "Mark 'Ordered'");

define('discount_for', "With Discount:");

define('curr_build', "Current build");
define('category_useweb_header', "Web");

define('icon_unpublish', "Click to UnPublish");

define('reset_to_main', "Tick_to_reset_to_main_event.");

define('send_order_post', "Mark 'Sent'?");

define('prices_in', "Prices in");

define('version_missing', "missing");

define('category_usepos_header', "POS");

define('icon_unpublish_alt', "Published");

define('ort_admin_tab', "Venues");

define('no_send_order_post', "Mark 'Not Sent'");

define('please_login', "Please Login or Register to Reserve Seats.");

define('are_you_sure', "Do you want to download update?");

define('pm_maroc_url', "pm_maroc_url");
define('pm_name_header', "Name");

define('icon_publish', "Click to Publish");

define('ort_admin', "Venues");

define('change_order_to_paid', "Mark 'Paid'");

define('select_category', "Select a Category");

define('are_you_sure_update', "Do you want to download update?");

define('pm_mollie_partnerid', "pm_mollie_partnerid");

define('template_name_header', "Template");

define('icon_publish_alt', "New Event");

define('ort_title', "Venues");

define('change_order_to_send', "Mark 'Sent'");

define('order_limit', "Order Limit");

define('are_you_sure_apply_update', "Do you want to apply update? YOU WILL LOOSE CUSTOM CHANGES!");

define('pm_mollie_test', "pm_mollie_test");

define('ort_city_header', "City");

define('icon_nosal', "Click to RePublish");

define('ort_add_title', "Add Venue");

define('change_order_to_no_paid', "Mark 'Not Paid'");

define('old_event', "This event is expired and can not be ordered anymore.");

define('shopconfig_ftusername', "fusionticket.org Username");

define('bank_id', "bank_id");

define('admin_status_header', "Kind");

define('icon_nosal_alt', "UnPublished");

define('ort_insert_title', "Add Venue");

define('reissue_order_menu', "Update this Order and Issue with new tickets.");

define('select_seat_head', "Select your seat(s)");
define('shopconfig_ftpassword', "fusionticket.org Password");

define('uninstall', "Uninstall");

define('admin_login_header', "Loginname");
define('add_tooltip', "Add");

define('ort_update_title', "Modify Venue");

define('cancel_order', "Mark 'Canceled' and Delete Tickets");

define('select_seat', "1. Select your seat(s)");
define('shopconfig_keepdetails', "Save User/Pass/Proxy Settings?");

define('install', "Install");

define('admin_country_header', "Country");
define('add_multi_tooltip', "Add sub-event to this main event.");

define('ort_id', "Venue ID");

define('select_seat_pos', "Select your seat(s) for ");

define('download_update', "Update Settings and Apply");

define('bill', "Bill");

define('discount_name_header', "Discount name");

define('edit_tooltip', "Edit Item");

define('ort_name', "Venue Name");

define('templ_email', "Emails");

define('click_on_reserve', "2. Click on 'Reserve'");

define('shopconfig_proxyaddress', "Updater optional proxy address.");

define('others', "Others");

define('discount_promo_header', "Promo code");

define('add_venue_tooltip', "Add a new Venue");

define('ort_address', "Address");

define('templ_swift', "Simple Email");

define('number_seats', "Number of seats");

define('shopconfig_proxyport', "Update proxy port.");

define('report_eventbarcodes', "List of Barcodes per event");

define('discount_value_header', "Value");

define('compile_all_tooltip', "This will (re)compile all the templates to check they are valid.");

define('ort_address1', "Address 1");

define('templ_pdf2', "Html2pdf's");

define('only_rows_numbered', "Only rows numbered");

define('downloaded_update_files', "Downloaded Update Files:");

define('export_eventbarcodes_title', "List of Barcodes per event");

define('discount_used_header', "Used");

define('copy', "Copy");

define('ort_zip', "Zip");

define('templ_pdf', "Old Pdf's");

define('order_reg', "Order Registered");

define('download_older_than_curr', "Available Update is older than currently installed!");

define('export_eventbarcodes_event', "Select Event");

define('discount_useweb_header', "Web");

define('add_pm', "Add Placemap");

define('ort_city', "City");

define('template_title', "Templates");
define('tnx_order_mess', "Thank you very much! Your order was registered. To pay for your order follow the proccess below. ");

define('download_same_as_curr', "Available Update is same as currently installed!");

define('eventbarcodes_date', "Date");

define('discount_usepos_header', "POS");

define('pm_split', "Split Placemap");

define('ort_state', "State");

define('template_add_title', "Add a Template");

define('shopping_cart_check_out', "Select Payment & Shipment Method");

define('download_link_failed', "Could not get download link");

define('eventbarcodes_time', "Time");

define('user_city_header', "City");

define('split_zones', "Split Zones");

define('ort_country', "Country");

define('template_update_title', "Modify Template");

define('handling_cont_mess', "Check your tickets, Check your details and then select your payment option and click &quot;Order&quot;.");

define('file_download_failed', "Failed to download file, try again later");

define('export_eventbarcodes_code', "Barcode");

define('user_country_header', "Country");

define('ort_phone', "Phone");

define('lang', "Language");

define('handlings', "Payment Methods");

define('file_downloaded', "Update.zip downloaded");

define('export_eventbarcodes_fullname', "Patron");

define('user_posname_header', "POS Office");

define('place_map_tooltip', "Edit Event Seating and Discounts");

define('ort_fax', "Fax");

define('lang_en', "English");

define('payment', "Payment");

define('file_saved', "Update.zip Saved");

define('entrant_date', "Date");

define('user_id_header', "ID");

define('archive', "Archive");

define('ort_url', "Homepage");

define('email_from', "From:");

define('shipment', "Shipment");

define('file_deleted', "Finished with Update.zip, removed.");

define('entrant_time', "Time");

define('user_name_header', "Username");

define('details', "Details");

define('ort_pm', "Googlemaps link");

define('email_to', "To:");

define('order_not_found_or_created', "Cannot proceed with order.");

define('update_save', "Update and/or Save Details");

define('nav_first-tooltip', "");

define('user_status_header', "Status");

define('print', "Print");

define('ort_image', "Venue Logo");

define('email_subject', "Subject");

define('limit', "Unfortunately, you have exceeded the amount of allowed reserved tickets.<br> To check your orders click <a href='index.php?action=person_orders'>here</a>.");

define('version_updater', "Update");

define('nav_prev-tooltip', "");

define('sales_patron', "POS Patron");
define('set_status_ord', "Set to Ordered");

define('place_maps', "Seat Charts");

define('email_text', "Text Section");

define('orclick', " Or Click to:");
define('order_already_crated', "This order is already saved!");

define('nav_next-tooltip', "");

define('tickets_reissued_remember_to_send', "Tickets reissued remember send!");

define('set_status_shipment_send', "Set to Sent");

define('edit_pm', "Modify Seat Chart");
define('email_html', "HTML Section");

define('pay_accept', "Payment Accepted");

define('order_already_cancelled', "This order has already been cancelled");

define('nav_last-tooltip', "");

define('status_header', "");
define('set_status_shipment_none', "Set to Not Sent");

define('pm_id', "Seat Chart ID");

define('template_id', "ID #");

define('pay_refused', "Payment Refused");

define('select_seat_title', "Select seat");

define('in_use_adminlink', "Record is connected to an event");

define('set_status_payment_paid', "Set to Paid");

define('pm_event_id', "Event ID");

define('template_type', "Type");

define('pay_reg', "Congrats! Your order was successfully made.");

define('freeticketcode_notfound', "FreeTicketCode not found. Try again");

define('ismember', "ismember");

define('config_errors_found', "Check your configuration, there where some errors found while saving.");

define('set_status_payment_none', "Set to Not Paid");

define('pm_name', "Seat Chart Name");

define('template_name', "Name");

define('pay_reg_desc', "Your electronic ticket has been sent to your email address.<br/><br/> Please make sure you have a printed copy to present when collecting your physical ticket.<br/><br/><span>Note: if you don't find your electronic ticket in your inbox please check your Spam/Junk folder or <a href='contact.php'>contact us</a>. To avoid our emails being seen as junk, please add our 'From' address to your Address Book.</span>");
define('placemap_image_explanation', "<img class='seatmapimage' src=\"{$_SHOP->images_url}seatfree.png\">: Available choice,
                                     <img class='seatmapimage' src=\"{$_SHOP->images_url}seatselect.png\">: Selected,
                                     <img class='seatmapimage' src=\"{$_SHOP->images_url}seatused.png\">:  Unavailable,
                                     <img class='seatmapimage' src=\"{$_SHOP->images_url}seatdisable.png\">: Other category");

define('captcha_info', "Enter this code >>>");

define('error_salespoint_not_found', "Error: Salespoint not found!!");

define('save_payment_tooltip', "Save &amp; Email the above note to the customer.");

define('pm_image', "Seat Chart Image");

define('compile_all', "Compile all");

define('pay_error', "Payment Declined</p><p>Your online transaction has been declined by your bank. Please read the following reasons why this could have happened.<br/><br/><ul><li>1.  Insufficient funds in your bank account.</li><li>2.  Your bank has declined the payment due to 'Stop Payments' as a precautionary measure against fraudulent credit card use.</li><li>3.  The credit card details were entered incorrectly.</li></ul><br/></p><p>If you are sure the credit card details are correct please try again later or contact us at {$organizer_email} for further assistance. Please accept our apologies for any inconvenience caused by the error when completing your ticket purchase.");

define('copy_main_pm', "copy from main event");

define('user_condition', "Conditions: Information collected will only be stored to handle shipping and payment.");

define('plugin_info_header', "Plugin");

define('save_ship_tooltip', "Save &amp; Email shipping note");

define('categories', "Categories");

define('email_to_name', "Email to name:");

define('trx_id', "Transaction ID");

define('republish_old_event', "Are you sure you want to publish this archived event?\\r\\n It will only show in the [Program] area of the Web Shop.");

define('pdf_tickets_and_invoice', "pdf_tickets_and_invoice");
define('plugin_myversion_numbering_header', "Version");

define('save_note_tooltip', "Save &amp; Email a note");

define('both', "Rows/Seats");

define('email_to_email', "To email address:");

define('orderdeleted', "Order Deleted");

define('unpublished', "UnPublished");

define('pdf_invoice_only', "pdf_invoice_only");
define('plugin_author_header', "Author");

define('delete_ticket', "Delete Ticket");

define('rows', "Rows");

define('email_from_name', "Email from name:");

define('printinvoice', "Print Invoice");

define('restart__failure', "restart__failure");

define('pdf_tickets_only', "pdf_tickets_only");
define('priority_header', "Priority");

define('nav_first', "First");

define('seat', "Seats");

define('email_from_email', "From email address:");

define('printtickets', "Print Tickets");
define('plugins_tab', "Plugins");

define('order_is_not_paid', "Order not Paid.");

define('pmp_name_header', "Name");

define('nav_prev', " < ");
define('none', "None");

define('emails_cc', "CC emails:");

define('free_event', "Free Tickets");

define('category_pm_id', "Seat Chart ID");

define('seat_checked', "Seat checked");

define('pmp_size_header', "Size");

define('nav_next', " > ");

define('cat_at', "@");

define('emails_bcc', "BCC emails:");

define('discounts', "Discounts");

define('category_pmp_id', "Seat Chart Part ID");

define('event_ordering', "Order tickets");

define('zones_name_header', "Name");

define('nav_last', "Last");

define('category_id', "Category Number");

define('email_def_lang', "Default template language:");

define('place_nr', "Seat");
define('publish7', "publish7");

define('event_ordering-tooltip', "");

define('zone_short_header', "Short");

define('password', "Password");

define('category_name', "Category Name");

define('email_templates', "Email templates:");

define('unassigned_seat', "Unassigned");

define('pub__failure', "The following event failed to publish:");

define('event_select_cat', "Select Category");

define('uadmin_inuse_header', "Active");

define('password1', "Choose Password");

define('category_price', "Category Price");

define('remove_group', "Remove");

define('each', "per ticket.");
define('export_entrant_withseats', "Export with seat numbers");
define('event_select_seats', "Seatmap");

define('free_seat_cat', "Seats Available:");

define('password2', "Repeat Password");

define('category_template', "Template for Tickets");

define('template_subject', "Template language subject");

define('shop', "Order Tickets");

define('export_entrant_notsended', "Include seats not yet sent");

define('select_discounts', "Select Discount");
define('search_orderid', "Order ID");

define('new_password', "New Password");

define('category_color', "Color for Category");

define('template_text', "Template language plain text");

define('shop_main', "Select Event");

define('mollie_status_cancelled', "You have cancelled the order while in iDeal");

define('no_discount', "No discount");

define('search_patron', "Patron");

define('old_password', "Current Password");

define('category_numbering', "Category Numbering");

define('template_html', "Template language HTML");

define('shop_info', "Check tickets are available for the desired Category then click on &quot;Buy Tickets&quot; to continue.");

define('always_show_handling', "Show always");

define('bad_category_id', "Category not found.");

define('search_phone', "Phone");

define('confirmpassword', "Confirm Password");
define('category_numbering_both', "Rows and Seats Numbered");

define('send_test', "Send Test Email");
define('shop_info_main', "Select a event below for the day for which you wish to purchase tickets.");
define('shopconfig_maxorder', "Max tickets to order");

define('next', "next");

define('search_email', "eMail");

define('event', "Event");

define('category_numbering_rows', "Only Rows Numbered");

define('email_header', "Email Header");

define('shop_condition', "Conditions: Information collected will only be stored to handle shipping and payment.");

define('unable_to_fetch_seats', "Unable to fetch Users seats");

define('add_to_cart', "Add to Cart");

define('pos_waitingmessage', "Waiting for payment..");

define('home', "Home");

define('category_numbering_seat', "Only Seats Numbered (No Rows)");

define('email_body', "Email Body");

define('shop_no_event', "Sorry but the event you are looking for, does not exist, has expired or been removed.");

define('user_seat_update_failed', "Unable to update User seat numbers");

define('error_cantloadevent', "can't load selected event");

define('receipt', "Receipt.");

define('logout', "Log out");

define('category_numbering_none', "Seats w/o Numbers (Open Seating)");

define('fees', "Fee's");
define('from', "From the");

define('unable_to_update_user_details', "Unable to update User details");

define('buy_tickets', "Buy Tickets");

define('tickettaker', "Ticket Taker");

define('member', "Member login");

define('category_size', "Category Size");

define('shipment_fees', "Shipment fees");

define('choose_event', "Please select the event for the day you wish to book from the list below:");

define('input_fields_requered', "Input fields with a <b>*</b> are required.");

define('linked_posoffices', "POS Offices");

define('no', " No");
define('number_taken', "Seats Sold");

define('handling_title', "Order Handling");

define('doors_open', "Doors Open");

define('cant_delete_image', "Cannot delete image file");

define('person_user', "Profile details");

define('unlink', "unlink");

define('order_id', "Order Number");

define('category_data', "Category Data");

define('handling_add_title', "Add an Order Handling");

define('dates_localities', "Dates and Locations");

define('cant_delete_mp3', "Cannot delete mp3 file");

define('person_orders', "List of orders");

define('spoint_removed_adminuser', "The pos user/manager is unlinked from this Office.");

define('remove_image', "Remove File or Image");

define('category_new_size_title', "Change Category Size");

define('payment_update_title', "Modify the Payment Type");

define('various_dates', "Multiple Dates");

define('enabled', "Enabled");

define('printticket', "Print Ticket(s)");

define('tospage', "ToS");
define('tickets', "Tickets");

define('category_new_size', "New Size");

define('handling_update_title', "Modify the Payment Type");

define('venue', "Location");

define('show_stat_reports', "Other Reports");

define('with_discount', " with ");

define('tos_title', "Change ToS page");

define('welcome', "Welcome");

define('pm_zones', "Zones");

define('handling_payment', "Payment");

define('no_sub_events', "There are no sub-events currently available.");

define('report_admin_title', "Spreadsheet Reports");

define('edit_user', "Edit");

define('tos_text', "Discription");

define('yes', " Yes");

define('pm_zone', "Zone");

define('cash', "Cash");

define('no_categories_available', "There are currently no categories currently available online. Contact the Box Office direct.");

define('report_xl', "Tickets Sales Report");

define('user_update', "Save profile");

define('tos_document_saved', "The ToS document is changed");

define('user_firstname', "First Name");

define('pmz_pm_id', "Seat Chart ID #");

define('entrance', "At the Entrance");
define('event_groups', "Event Groups");

define('report_archive_event', "Event Archives");

define('failed_too_update_user', "failed to update userprofile");

define('netpay', "netPay");

define('user_lastname', "Last Name");

define('pmz_color', "Zone Color");

define('invoice', "Invoice");

define('et_church', "Church Music");

define('report_entrant', "Ticket Status Report");

define('order_info', "Order overview");

define('pm_netpaypal_secure', "Netpay's securecode");

define('user_name', "Name");

define('pmz_name', "Zone Name");
define('paypal', "PayPal");

define('et_cinema', "Cinema");
define('export_statuslog', "Export Status Log");

define('invalid_order', "invalid_order");

define('pm_netpaypal_id', "Netpay's  merchant ID");

define('user_address', "Address");

define('pmz_short_name', "Zone Nickname");

define('ideal', "iDEAL");

define('et_classics', "Classical Music");

define('max_seats_reached', "Maximum Seats Reached");

define('submit_reserve', "Reserve");

define('netpay_pay', "Click here go to NetPay payment page.");

define('user_address1', "Address 1");

define('pmz_id', "Zone Record Number");

define('authorize_aim', "AIM");

define('et_expo', "Expo");

define('handling_alt_settings', "Alternate Settings");

define('go_home', "Home");

define('placemap_delete_failed_seats_exists', "Cannot delete seatmap. Event belonging to this seatmap is published already!");

define('user_address2', "Address 2");

define('pmz_ident', "Zone Number");

define('ebs', "EBS");
define('et_folk', "Folk");

define('hide', "Hide");

define('go_pay', "Pay order");

define('pos_user_not_connected', "<font color=red>Not Linked</font>");

define('user_city', "City");

define('place_map', "Seat Chart");

define('email', "Email");
define('et_humour', "Humour");

define('handling_fee_settings', "Fee Settings");

define('user_email2', "Repeat E-Mail");

define('pos_user_connected_to', "");

define('user_state', "State");

define('pm_parts', "Seat Chart Parts");
define('post', "Post");

define('et_jbf', "Jazz/Blues/Funk");

define('hanging_pdf_settings', "PDF Settings");

define('order_reserved', "Order is reserved for you");

define('admin_user_id_blank', "There isn't a selected user.");

define('user_state_name', "State");

define('pm_part', "Seat Chart Part");

define('google', "Google");

define('et_music', "Music");

define('hanging_email_settings', "Email Settings");

define('cart_expired', "The tickets in you cart are expired and will be removed from the cart.");

define('pm_img_file_not_found', "The image for the placemap can't be found");

define('user_zip', "Zipcode");

define('pmp_id', "Seat Chart Part ID");

define('handling_shipment', "Shipment");

define('et_opbal', "Opera/Ballet");

define('plugins_title', "Plug Ins");

define('vertical_menu', "Menu");

define('img_loading_problem_ext', "The chosen extension is not allowed by the system");

define('user_country', "Country");

define('pmp_name', "Seat Chart Part Name");

define('handling_sale_mode', "Selling Method");

define('et_other', "Other");

define('plugin_email', "Email: ");

define('no_orderid_given', "No Order ID for ticket loading");

define('allow_free_tickets', "Allow free ticket categories");

define('user_country_name', "Country");

define('pmp_width', "Seat Chart Part Width");

define('www', "Webshop");

define('et_party', "Party");

define('plugin_web', "Website: ");

define('select_user_country', "[Select Country...]");
define('shoppos_settings', "POS Office settings");

define('user_phone', "Phone");

define('pmp_height', "Seat Chart Part Height");

define('sp', "POS");

define('et_pr', "Pop/Rock");

define('order_status_send', "Sent");

define('cant_lock_seat', "can't lock seat");

define('shoppos_allow_without_fee', "Allow All POS offices to sell free tickets");

define('user_fax', "Fax");

define('pmp_scene', "Scene Location");

define('handling_alt', "Alt Handling Method");

define('et_theater', "Theatre");

define('promo_in_use', "This promocode is already used.");

define('search_choice_two_fields', "Fill atliest 2 fields.");
define('shoppos_allow_without_cost', "Allow All POS offices to sell tickets without fee");

define('user_email', "E-Mail");

define('pmp_scene_none', "None");

define('handling_no_alt', "Hide");

define('forgot_pwd', "Forgot Password ?");

define('discount_promo_for', "Discount promocode for&nbsp;");

define('personal_search_dialog', "Personal Search dialog");
define('preview_webshop', "Preview Website");

define('user_id', "User ID");

define('pmp_scene_north', "North");

define('handling_alt_only', "Only Alt Handling Method");

define('pwd_forgot', "Forgotten your Password?");

define('rep_ord_id', "Order #");

define('order_status_reserved', "Reserved");

define('pm_part_preview', "Seat map part preview");

define('user_status', "Status");

define('pmp_scene_east', "East");

define('handling_expires_min', "Minutes until OH Cancels for<br> Non-Payment (0 = Never)");

define('forgot_password', "Forgotten your Password?");

define('rep_sale_date', "Sale Date");

define('order_status_sent', "Order sent");

define('placemap_seats_selected', "Selected Seats: ");

define('user_maillist', "Newsletter");

define('pmp_scene_south', "South");

define('handling_fee_fix', "Fee Fixed");

define('forgot_password_ok', "Your password has been reset");

define('rep_sale_barcode', "Barcode");

define('order_status_paid', "Order paid");

define('has_eventpromo', "Use promocode");

define('act_err', "User Not Found or Already Activated!");

define('pmp_scene_west', "West");

define('handling_fee_percent', "Fee Percent");

define('forgot_password_ok_desc', "OK ! We have generated a new password for you and sent it to your email.");

define('hand_payment_text', "Payment Method");

define('order_status_cancelled', "Order cancelled");

define('enter_eventpromocode', "Please Enter Promocode below.");

define('act_error', "Account Could Not be Activated! Please re-check the link or contact the system administrator.");

define('pmp_shift', "Shift Rows");

define('handling_email_template_ord', "Email to send when Ordered");

define('pwd_err', "User not found or other problem occurred");

define('user_title', "Customer Information");

define('success', "Success ");

define('eventdiscount_invalid', "Promo code is invalid.");

define('act_uselink', "Please use the link that has been sent to your email address.");

define('scene_h', "../images/scene_h_en.png");

define('handling_email_template_send', "Email to send when Shipped");

define('pwd_is_sent', "Your new password was sent to your e-mail");

define('cust_id', "ID");

define('invalid', "Invalid");

define('posuser_activate', "Register all Pos Users as Member");

define('act_email_sent', "Activation email sent.");

define('scene_v', "../images/scene_v_en.png");

define('handling_email_template_paid', "Email to send when Paid");

define('pwd_note', "Enter your e-mail address here. Click on 'Send Password' and a new password will be emailed to you");

define('ven_id', "ID");

define('select', "Select");

define('placemap_selection', "Map");

define('already_exist', "This Name Already Exists. Choose Another!");

define('label', "Label:");

define('handling_pdf_template', "PDF Template for Invoice/Receipt");
define('helpme', "Help information");

define('ven_name', "Name");

define('garbage_logfiles', "Overview of create log files");

define('reserve_tickets', "Tickets are Reserved");

define('useralreadyexist', "This E-mail is Already Registered in the Database!");

define('label_type_text', "Text");

define('handling_pdf_ticket_template', "PDF Ticket Template");

define('up_events', "Upcoming Events");

define('evnt_title', "Event Information");

define('no_logfiles_find', "There are no log files precent");

define('order_place_header', "Method");

define('autocancel_order', "Auto Cancel: Failed to Order!");

define('label_type_row_east', "Row# on Right");

define('handling_text_payment', "Payment Label");

define('eventlist_info', "Please select an upcoming event from below.");
define('evnt_id', "ID");

define('clear_cache', "Clear Cache");

define('pmp_zone_name_header', "Zone");

define('autocancel_paying', "Auto Cancel: Failed to Pay for Order!");

define('label_type_row_west', "Row# on Left");

define('handling_text_shipment', "Shipment Label");

define('orders', "Orders");

define('evnt_name', "Name");

define('garbage_files', "Orphaned/Misc Files");

define('pmp_category_name_header', "Category");

define('cant_delete_self', "You can not delete yourself!");

define('label_type_seat_south', "Seat# Below");

define('handling_html_template', "HTML Template for Explanations");

define('order_summary', "Order Summary");

define('evnt_date', "Date");

define('delete_files', "Delete all files");

define('pm_category', "Category");

define('cannot_find_seat', "Cannot Find Seat!");

define('label_type_seat_north', "Seat# Above");

define('handling_email_template_ord_incl_pdf', "Include PDF's for Order");

define('personal_orders', "Personal Orders");

define('evnt_time', "Time");

define('no_files_found', "There are no orphaned/misc files");

define('edit_seatnumbering', "Edit Seat numbering");

define('cannot_seal', "Internal Error: Cannot Seal Credit Card Info!");

define('label_type_exit', "Exit");

define('handling_email_template_paid_incl_pdf', "Include PDF's for Paid");

define('number_tickets', "Number of tickets");

define('cat_title', "Ticket Information");

define('handling_fee_perseat', "fixed fee per seat");

define('add_zone_seat', "Add seat to this zone");

define('cannot_store', "Internal Error: Cannot Store Credit Card Info!");

define('seat_numbering', "Seat Numbering");

define('handling_email_template_send_incl_pdf', "Include PDF's for Sent");

define('userid', "User Id");

define('cat_id', "ID");
define('config_title', "Configuration Tables");

define('add_category_seat', "Add to this category");

define('check_condition', "Please Accept the Terms!");

define('autonumber_pmz', "Automatic numbering");

define('handling_email_template_ord_incl_inv_pdf', "Invoice/Receipt");

define('buytimeleft', "You have ~DAYS~ Days, ~HOURS~ Hours, ~MINS~ Mins, ~SECS~ Seconds left to confirm your order!");

define('cat_name', "Name");

define('group_organizer', "Merchant Details");

define('select_category_first', "Select Category first.");

define('compilation_succeed', "Success - Template Compiled!");

define('first_row', "First Row");

define('handling_email_template_paid_incl_inv_pdf', "Invoice/Receipt");

define('autocancel', "After this time your order is automatically cancelled!");

define('cat_price', "Value");

define('group_common', "Common");

define('placemap_seats_of', "of");

define('correct_errors_first', "Correct Errors First!");

define('step_row', "Row Step");

define('handling_email_template_send_incl_inv_pdf', "Invoice/Receipt");

define('ordertickets', "To Order Tickets Click below:");

define('cat_sold', "Sold For");

define('landscape', "Landscape");

define('event_ordering_tickets_info', "Ordering <b id=ordering_seats class=seatscounter>0</b> x <b id=ordering_category></b> with <b id=ordering_discount></b> a <b id=ordering_price></b> = <b id=ordering_total></b>");

define('delete_confirm_msg', "Delete This Event?");

define('inv_row', "Invert Rows");

define('handling_email_template_ord_incl_ticket_pdf', " Ticket");

define('reserv_cancel', "WARNING this is a one way process!");

define('disc_name', "Name");

define('system_online', "System on-line");

define('available', "Available");

define('delete_item', "Delete?");

define('first_seat', "First Seat");

define('handling_email_template_paid_incl_ticket_pdf', " Ticket");

define('notpaid', "Not Paid");

define('disc_type', "Type");

define('offline_message', "Off-line message");

define('all', "All");

define('deleted_all_tickets', "Deleted All Tickets!");

define('step_seat', "Seat Step");

define('handling_email_template_send_incl_ticket_pdf', " Ticket");

define('sold', "Sold");

define('disc_value', "Value");

define('secure_site', "Security");

define('onone_isprivate', "(Private Note)");

define('delete_subs_first', "Delete Sub-Events First!");

define('inv_seat', "Invert Seat");

define('handling_only_manual_send', "Always manually send email");

define('manual_payment', "Set to Paid: ");

define('handling_fee_type', "Fee calculation type");

define('theme_name', "Theme name");

define('print_address', "Print Address Label");

define('email_valid', "Please Enter a Valid Email Address!");

define('flip', "Flip");

define('pm_paypal_business', "PayPal Account");
define('payhere', "<br><br>To Pay Now, Check Here:");

define('handling_fee_sum', "Sum of fixed and Percent");

define('input_time_type', "Time Format");

define('email_match', "The Emails Do Not Match!");

define('keep', "Keep");

define('pm_paypal_test', "PayPal Sandbox");

define('notsent', "Not Sent");

define('handling_fee_min', "Minimum of fixed and Percent");

define('time_type_12', "12 hour clock");

define('cant_find_seat', "Can't find seat");

define('email_badconfig', "The program's mail configuration is incorrectly defined!");

define('map', "Chart");

define('pm_ideal_merchantid', "Merchant ID");

define('sent', "Sent");

define('handling_fee_max', "Maximum of fixed and Percent");

define('time_type_24', "24 hour clock");

define('cant_update_event_stat', "Cannot update the event statistics");

define('event_order_limit_exceeded', "Sorry, The number of seats that you can order for this event is limited!");

define('ort', "Venue");

define('pm_ideal_subid', "Sub ID");

define('go_back', "Click Here to Go Back");

define('pay_ispending', "Payment transaction is pending.");

define('input_date_type', "Date format");

define('freeticketcode', "Discount Code:");
define('fax_short', "The Fax Number is too Short!");

define('ort_plan_nr', "Number on plan");

define('pm_ideal_issuer', "Issuing Bank");

define('id', "ID");

define('cookie_disabled', "<h1> Warning, you have disabled cookies on your system.</h1> This will not work on this website. Please turn this on, before you order any tickets.</h1>");

define('date_type_dmy', "ddmmyyyy");

define('infogetfilefunction', "InfoGetFileFunction");

define('fax_long', "The Fax Number is too Long!");

define('event_group_tab', "Event Groups");

define('pm_ideal_test', "Ideal Sandbox");

define('zone', "Zone");

define('admin_user_id', "Sale Point user");

define('date_type_mdy', "mddyyyy");

define('infoziplibinstalled', "InfoZipLibInstalled");
define('img_loading_problem', "Problem Loading Image!");

define('event_group_title', "Event Groups");

define('pm_ideal_key', "Key");

define('discount', "Discount");

define('admin_status', "Role of user");

define('date_type_ydm', "yyyyddmm");

define('orderdescription', "Fusion Ticket Order ");

define('img_loading_problem_copy', "Problem Loading Image Copy!");

define('event_group_add_title', "Add an Event Group");

define('pm_ideal_keypass', "Key Password");
define('paytimeleft', "You have ~DAYS~ Days, ~HOURS~ Hours, ~MINS~ Mins and ~SECS~ Seconds to pay for your order!");

define('admin_email', "Email address");

define('timezone', "Time zone");

define('pm_vpc_accesscode', "pm_vpc_AccessCode");

define('in_use', "This Object is in use and <b>cannot</b> be Deleted!");

define('event_group_update_title', "Modify Event Group");

define('pm_ideal_pcert', "Pcert");
define('paytimeforever', "You have to pay for your order, before the start of the event! ");

define('admin_posuser_title', "Sale Point Administrators");

define('pdf_paper_size', "Pdf Paper size");
define('pm_vpc_merchant', "pm_vpc_Merchant");

define('internal_error', "Internal Error!");

define('event_group_id', "Group ID");

define('pm_ideal_certficate', "Certificate");
define('pers_orders', "Current / Previous Order");

define('user', "user");

define('pdf_paper_orientation', "Orientation");
define('pm_vpc_secure_secret', "pm_vpc_SECURE_SECRET");

define('invalid_date', "Invalid Date!");

define('event_group_name', "Group Name");

define('pm_google_merchant_id', "Merchant ID");

define('options', "Options");

define('shipment_type', "Shipment Type");

define('portrait', "Portrait");

define('english', "English");

define('invalid_number', "Invalid Credit Card Number!");

define('event_group_start_date', "Start Date");

define('pm_google_merchant_key', "Key");
define('pers_cancel', "Cancelled");

define('shipment_address', "Shipment Address");

define('address_label_template', "Address Label Template");

define('log_err_isactive', "That account is already active.");

define('event_group_end_date', "End Date");

define('pm_google_sandbox', "Sandbox");
define('pers_ord', "Ordered/Unpaid");

define('order_owner_id', "Create by POS");

define('address_label_always', "Always print an address label");

define('log_err_mailnotsend', "The Activation Email <b>could not</b> be sent, please check you have entered the correct email address.");

define('event_group_type', "Group Type");

define('pm_google_callback_link', "Call Back Link");
define('pers_page', "Personal Page");

define('onote_type_note', "note");

define('trace_on', "Trace-on");

define('log_err_not_act', "You are Not Activated!");

define('festival', "Festival");

define('pm_on_google_cancel_cancel_order', "Google Cancellation");
define('pers_paid', "Paid");

define('onote_type_admin', "admin");

define('shopconfig_run_as_demo', "Run as Demo");

define('log_err_not_act_info', "Your account is not yet activated.
  <p>Please check your email to activate your account. Don't forget to check the spam folder.</p>
  <p>If you haven't received any email yet, please click <a href='resend_activation.php'>here</a> to resend the activation email.</p>");

define('tournee', "Tournament");

define('pm_on_user_cancel_cancel_order', "User Cancellation");
define('pers_reissue', "Re-issued");

define('onote_type_payment', "payment");

define('group_autocleanup', "Auto clean-up");

define('log_err_wrong_usr', "Your username and/or password don't match!");

define('theatre', "Theater");

define('pm_on_refund_cancel_order', "Refund");
define('pers_res', "Reserved");

define('onote_type_todo', "todo");

define('group_ordering', "Ordering");

define('log_err_wrong_usr_info', "Wrong Username or Password.
		If you have forgoten your password, click <a href='forgot_password.php' onclick='showDialog(this);return false;' >here</a>");

define('event_group_description', "Description");

define('pm_ebs_accountid', "Account ID");
define('pers_send', "Sent");

define('onote_isprivate', " (<i>private</i>)");

define('group_upload', "Upload settings");

define('mand_all', "All input fields are Required.");

define('event_group_image', "Event Group Image");

define('pm_ebs_seckey', "Security Key");
define('pers_unknown', "Unknown Status - Contact Admin");

define('onote_private', "Personal Note (You can see only)");

define('allowed_uploads', "Allowed file types");

define('mandatory', "Field Required!");

define('unpublish_event_group', "Unpublish Event Group");

define('pm_ebs_test', "EBS Test");
define('personal', "Personal Details");

define('onote_subject', "Note Subject");

define('file_mode', "File mode");

define('mp3_loading_problem', "Problem Loading MP3 File!");

define('publish_event_group', "Publish Event Group");
define('pm_authorize_aim_login', "AIM Login");
define('pers_mess', "To change your details please click the [Edit] button below.");

define('onote_note', "Note Details");

define('allowed_maxsize', "Maximum size");

define('missing_pm_ord_id', "Error: this placemap cannot be saved, venue is missing");

define('event_tab', "Events");

define('pm_authorize_aim_txnkey', "Transaction Key");
define('pers_mess2', "To change or see your orders in more detail please click <a href='index.php?personal_page=orders'>Here</a><br><br>Only the last 6 orders are shown here.");

define('onote_set_sent', "On &quot;Save &amp; Email&quot; Set Order To Sent.");

define('allowed_maxwidth', "Maximum width");

define('nosale_confirm_msg', "Remove from Sale?");

define('history_tab', "Archive");

define('pm_authorize_aim_test', "AIM Test");
define('payment_status', "Payment Status");

define('onote_set_paid', "On &quot;Save &amp; Email&quot; Set Order To Paid.");

define('allowed_maxheight', "Maximum height");

define('new_order_created', "New Order Created");

define('event_history_title', "Previous Events");

define('patron_tab', "Customer");

define('shipment_status', "Shipment Status");

define('onote_resend_sent', "Resend &quot;Sent&quot; Email.");

define('group_mail', "Mail settings");

define('not_number', "Enter a Number Without -()!");

define('event_title', "Active Events");

define('search_title_user', "Search for Customer");

define('program', "Program");

define('onote_resend_paid', "Resend &quot;Paid&quot; Email.");

define('mail_smtp_host', "Host");

define('not_valid_email', "E-mail is invalid.");

define('checkbox_all', "Check/Uncheck All");

define('sale_point', "POS");

define('div_dates', "Multiple Dates");

define('logged_in', "User:");

define('mail_smtp_user', "SMTP User");

define('no_result', "No Result!");

define('also_sub', "Subevents also");

define('guest', "Guest");

define('your_addr', "Shipment details");

define('placemap', "Event Placemap");

define('mail_smtp_pass', "SMTP Password");

define('old_order_cancelled', "Old Order Cancelled!");

define('event_add_title', "Add a New Event");

define('search_result', "Search Result");

define('confirmemail', "Confirm E-mail Address");

define('event_details', "Event Details");

define('mail_smtp_port', "SMTP Port");

define('order_allready_cancelled', "Order Already Cancelled!");

define('event_edit_title', "Modify Event");

define('seat_tab', "Seat");

define('login', "Login name");

define('event_view_periode', "Event Viewing Period");

define('mail_smtp_security', "Mail Security");

define('order_cancelled', "Order Cancelled!");

define('event_update_title', "Modify Event");

define('seat_status', "Status");

define('memberinfo', "Please enter your details below. To buy tickets you are required to sign up, it is recommend that you sign up before you reserve tickets.");

define('event_view_begin', "Event View Begin Date");

define('smtp_security_none', "none");

define('order_cannot_reissue', "Can Not Re-Issued!");

define('add_multi', "Add Sub-Event");

define('seat_code', "Barcode");

define('register', "Register");

define('event_view_end', "Event View End Date");

define('smtp_security_ssl', "ssl");

define('order_error_message', "Order Error Message");

define('event_id', "Event ID#");

define('search_title_place', "Search Seats");

define('alreadymember', "Already a Member?");

define('event_advanced_options', "Event Advanced Options");

define('smtp_security_tls', "tls");

define('order_madefinal', "Order is Complete");

define('event_name', "Event Name");
define('event_list', "Event List");

define('alreadymembertext', "Sign in to the site with your username and password on your left.");

define('event_pickup_options', "Event Pickup Options");

define('group_language', "Language");

define('order_not_found', "Order Not Found!");

define('event_pm_ort_id', "Seat Chart");

define('seat_row_nr', "Row Number");

define('becomemember', "Become a Member");

define('discount_deactivate', "Deactivate Discount");

define('langs', "Language code");

define('ordernotfound', "Order Not Found");

define('agenda_only', "Agenda Only");

define('seat_nr', "Seat Number");

define('pers_info', "Customer Information");

define('discount_activate', "Activate Discount");

define('langs_names', "Language Names");

define('order_not_cancelled', "Order Not Cancelled!");

define('event_ort_name', "Venue Name");

define('choice_please', "Choose Please...");

define('user_notice', "To order your tickets please complete the following fields and click on &quot;Continue&quot;. Fields with (*) are mandatory. This information will stay confidential. We will not give out your information or sell it to others. You can also choose to become a member and never fill this form again.");

define('print_invoice', "Print invoice");

define('event_type_enum', "Event type");

define('order_notice_message', "Order Notice Message");

define('event_rep', "Repeatability");

define('category', "Category");

define('becomememberorguest', "Register as Member or Guest");

define('print_tickets', "Print Tickets");

define('event_group_type_enum', "Event group");

define('order_paid_already', "Order Already Paid");

define('event_rep_main', "Multiple");

define('place', "Seat");

define('becomeguest', "Register as Guest");

define('adminlinks_pos_control', "Event Links");
define('autodefinelangs', "Auto-define language");

define('order_paid_total', "Total Paid");

define('event_rep_unique', "Unique");

define('price', "Price");

define('guest_info', "Fill your details here, so that the ticket can be sent to you.
					 <br> Already a regular customer? Fill at the left side, your email address and password.");

define('linked_tickettakers', "Linked ticket takers");

define('selectfunction_not_found', "Function not found");

define('pass_not_egal', "Passwords Do Not Match!");

define('main,sub', "Unique Event");

define('bs', "Ord.#");

define('pwd_min', " (min 6 letters)");

define('block', "Block Seats");

define('cant_save_configvalue', "Problem(s) while saving configuration setting for ");

define('pass_match', "Passwords do not match");

define('event_short_text', "Event Short Text");

define('status', "Status");

define('user_nospam', "Security Code");

define('assign', "Assign Seats");

define('change_order_to_paid_confirm', "Are you sure to set the order paid?");

define('pass_too_short', "Password is too short");

define('event_text', "Event Long Text");

define('order_tab', "Order");

define('nospam_info', "Enter this code >>>");

define('clear_selection', "Clear Selection");

define('error_while_registering_user', "There was an error while registering you. Please try again.");

define('phone_long', "The Phone Number is too long");

define('event_description', "Description");

define('search_title_order', "Search Orders");

define('agrement', "I have read and agree to the General Terms of Sale.");

define('reset', "Reset");

define('cant_send_email', "Problem while trying to send email.");

define('phone_short', "The Phone Number is too short");

define('event_url', "Homepage");

define('barcode_tab', "Barcode");

define('newsletter', "I would like to receive Weekly Virgin Megastore Mail");
define('name', "Name");

define('help', "Help");

define('places_empty', "Please select your seats");

define('event_date', "Date");

define('search_title_codebar', "Search Barcodes");

define('mayuse', "I agree that {\\$organizer_name} may use my details to send me information about future events and other {\\$organizer_name} related matters, and that they will not pass on my details to any 3rd party.");

define('size', "Size");

define('administrator', "Administration");

define('places_occupied', "The selected seats have been already reserved");

define('event_recur_type', "Re-Occurs");

define('codebar', "Barcode");

define('member_info', "Please enter your email address and password");

define('confirm_clear', "This operation will clear all your previously selected seat, are you sure you want to proceed?");

define('welcome_patron', "<b>Hi</b>");

define('places_remains', " Remaining seats");

define('recure_nothing', "No");

define('export_admin_title', "Export Data");

define('personaldetails', "Personal Details");

define('delete_link_error', "Can't delete an event link when there are seats allocated to this pos");

define('checked_by', "Checked by: ");

define('places_toomuch', "This Number of Seats cannot be Reserved!");

define('recure_daily', "Daily");

define('export_xml_event_title', "Export Data");

define('addressdetails', "Address Details");

define('mailer_description', "Use this interface to send emails to customers attending this event.");

define('checked_at', "Checked at: ");

define('pwd_not_thesame', "The Passwords Entered Do Not Match!");

define('event_recur_end', "Event Stops");
define('export_xml_event_submit', "Export It!");

define('contactdetails', "Contact Details");

define('mail_patrons_confirm', "Are you sure you want to email all attending customers?");

define('admin_realname', "Full Name");

define('pwd_second_missing', "Second Password is Missing!");

define('event_recur_end_error', "Date is invalid or older than start date");
define('export_xml_event_file', "Filename");

define('memberpasswords', "Passwords");
define('mail_patrons', "Mail Customers");

define('userewriteurl', "Create SEO urls");

define('pwd_to_short', "Password Too Short!");

define('recure_days_selection', "Days to Exclude");

define('export_xml_calendar', "Calendar");

define('securitytc', "Security and Terms");
define('select_template', "Select template");

define('userewriteurl-tooltip', "Create SEO urls");

define('pub_confirm_msg', "Publish Event?");

define('event_time', "Event Begins");
define('export_xml_calendar_event', "Calendar");

define('prg_order', "Order");

define('mail_to', "Mail to");

define('table_order_id', "Order");

define('reservate_failed', "Internal Error: Impossible to Save Seats ");

define('event_open', "Event Open");
define('export_templates', "Templates");

define('prg_seat', "Select Seat");

define('attending_patrons', "attending customer(s)");

define('table_order_price', "Amount");

define('restart_success', "Successfully Restarted!");

define('event_end', "Event Ends");
define('export_template_id', "Choose Template ");

define('prg_discounts', "Select Discounts");
define('preview_template', "Preview template");

define('table_order_user', "Patron");

define('save_successful', "Changes Saved");

define('event_order_limit', "Order Limit");
define('export_template_file', "Filename");

define('prg_review', "Cart");
define('please_select_template', "Please select a template.");

define('table_order_date', "Date/time");

define('save_failed', "Internal Error: Impossible to Save the Order ");

define('event_template', "Template for Tickets");
define('export_submit', "Export It!");

define('prg_signin', "Register");

define('send_email', "Send Email");

define('pdf_noting_to_show', "Nothing to show.");

define('send_order_email', "Send Order by E-mail and Change Status to 'Sent'");

define('event_type', "Event Type");
define('export_xml_event', "Event in XML");

define('prg_payment', "Select Payment");

define('no_attendants', "This event has no attendants yet.");
define('no_placemap_available', "No online sales. For informational purposes only");

define('select_handling_option', "Select a payment option.");

define('record_orphan_test', "Overview record orphans");

define('publish_pos', "Publish to POS");
define('published', "Published");

define('setlocale_all', "en.utf8; en.utf-8;en_EN.utf8;en_EN.utf-8;en-EN.utf8;en-EN.utf-8;en;en_EN;en-EN");

define('templ_system', "System Emails");

define('unpublish_pos', "Remove from POS");

define('pm_maroc_secretkey', "pm_maroc_SecretKey");
define('pm_maroc_storeid', "pm_maroc_storeId");
?>